'use client';
import { useCallback, useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { operationAttempt } from '@/lib/operationAttempt';
import { getLoyaltyAccount, redeemLoyaltyPoints } from '../actions';
type Account = { enabled: boolean; balance: number; canRedeem: boolean; policy: { earnMinorPerPoint: number; redeemMinorPerPoint: number; minimumRedemptionPoints: number } | null; entries: Array<{ id: string; points: number; type: string; description: string; createdAt: string }> };
export default function LoyaltyPanel({ bookingId }: { bookingId: string }) {
  const [account, setAccount] = useState<Account | null>(null), [points, setPoints] = useState(''), [message, setMessage] = useState(''), [busy, setBusy] = useState(false);
  const refresh = useCallback(async () => { try { setAccount(await getLoyaltyAccount(bookingId)); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load loyalty account.'); } }, [bookingId]);
  useEffect(() => { refresh(); }, [refresh]);
  async function redeem() { setBusy(true); setMessage(''); try { const request = { bookingId, points: Number(points) }, attempt = await operationAttempt('loyalty-redemption', request); const result = await redeemLoyaltyPoints(bookingId, request.points, attempt.key); attempt.complete(); setPoints(''); await refresh(); setMessage(`${result.pointsRedeemed} points applied as USD ${(result.amountMinor / 100).toFixed(2)} folio credit.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Redemption was not saved; retry the same request.'); } finally { setBusy(false); } }
  return <section className="space-y-2 rounded border p-3"><h3 className="font-medium">Loyalty points</h3>{account && <><p>{account.balance} available points</p>{account.enabled && account.policy ? <p className="text-sm text-muted-foreground">Earn one point per USD {(account.policy.earnMinorPerPoint / 100).toFixed(2)} of net settled payments, capped at eligible room charges, at completed checkout. Redeem points at USD {(account.policy.redeemMinorPerPoint / 100).toFixed(2)} each against an in-house guest-paid folio. Tax, fees, group master billing and redeemed value do not earn points. Successful refunds may reduce earned points, including a negative balance if points were already used.</p> : <p className="text-sm">Loyalty earning and redemption are not enabled. Existing ledger history is retained.</p>}{account.canRedeem && <div className="flex flex-wrap items-end gap-2"><label className="text-sm">Points to redeem<Input type="number" min={account.policy?.minimumRedemptionPoints || 1} step="1" value={points} onChange={event => setPoints(event.target.value)} /></label><Button disabled={busy || !points || Number(points) > account.balance} onClick={redeem}>Apply points to current folio</Button><p className="text-xs text-muted-foreground">Minimum {account.policy?.minimumRedemptionPoints} points; credit cannot exceed posted charges due. Redemptions are final folio credits.</p></div>}<details><summary className="cursor-pointer text-sm">Recent points history</summary><ul className="space-y-1 text-sm">{account.entries.map(entry => <li key={entry.id}>{entry.createdAt?.slice(0, 10)} · {entry.points > 0 ? '+' : ''}{entry.points} · {entry.description}</li>)}</ul></details></>}{message && <p role="status" className="text-sm">{message}</p>}</section>;
}
