'use client';
import React from 'react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { PageContainer } from '@/features/dashboard/components/PageContainer';
import { closeGroupMasterFolio, createGroupBlock, createGroupRoomingList, getGroupWorkspace, updateGroupStatus } from '../actions';
import { parseRoomingCsv } from '../lib/roomingCsv';
import { operationAttempt } from '@/lib/operationAttempt';
import GroupRecontract from '../components/GroupRecontract';

type Allocation = { id: string; roomsHeld: number; roomsPickedUp: number; rateMinor: number; roomType: { name: string } };
type Group = { id: string; name: string; blockCode: string; status: string; arrivalDate: string; departureDate: string; releaseDate?: string; billingType: string; allocations: Allocation[]; bookings: Array<{ id: string; confirmationNumber: string; guestName: string; status: string }>; masterFolio?: { id: string; folioNumber: string; status: string; entries: Array<{ amountMinor: number; direction: string }> } };
export default function GroupsPage() {
  const [workspace, setWorkspace] = React.useState<{ groupsEnabled: boolean; hasMore?: boolean; nextCursor?: string; groups: Group[]; roomTypes: Array<{ id: string; name: string; ratePlans: Array<{ id: string; name: string }> }> }>({ groupsEnabled: false, groups: [], roomTypes: [] });
  const [cursor, setCursor] = React.useState<string | undefined>();
  const [form, setForm] = React.useState({ name: '', arrivalDate: '', departureDate: '', releaseDate: '', contactName: '', contactEmail: '', billingType: 'guest_pays', roomTypeId: '', ratePlanId: '', roomsHeld: 1, rateDollars: '' });
  const [selectedGroup, setSelectedGroup] = React.useState(''), [csv, setCsv] = React.useState('rowId,guestName,guestEmail,numberOfGuests\nroom-1,Alex Guest,alex@example.com,1');
  const [message, setMessage] = React.useState(''), [busy, setBusy] = React.useState(false);
  const refresh = React.useCallback(async () => { try { setWorkspace(await getGroupWorkspace(cursor)); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load group workspace.'); } }, [cursor]);
  React.useEffect(() => { refresh(); }, [refresh]);
  async function perform(intent: string, operation: (key: string) => Promise<unknown>) {
    setBusy(true); setMessage('');
    try { const attempt = await operationAttempt('group', intent); await operation(attempt.key); attempt.complete(); await refresh(); setMessage('Group operation saved.'); }
    catch (error) { setMessage(error instanceof Error ? error.message : 'Group operation was not saved. Retry the same request.'); }
    finally { setBusy(false); }
  }
  function create() {
    const data = { ...form, arrivalDate: `${form.arrivalDate}T00:00:00.000Z`, departureDate: `${form.departureDate}T00:00:00.000Z`, releaseDate: form.releaseDate ? new Date(form.releaseDate).toISOString() : undefined, ratePlanId: form.ratePlanId || undefined, rateMinor: Math.round(Number(form.rateDollars) * 100), currencyCode: 'USD' };
    perform(JSON.stringify(data), key => createGroupBlock({ ...data, idempotencyKey: key }));
  }
  const selected = workspace.groups.find(group => group.id === selectedGroup);
  const roomType = workspace.roomTypes.find(type => type.id === form.roomTypeId);
  const money = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value / 100);
  return <PageContainer title="Group blocks" header={<div><h1 className="text-xl font-semibold">Group blocks and rooming lists</h1><p className="text-sm text-muted-foreground">Reserve room nights, confirm the contract, pick up guest rooms and settle the group&apos;s bill.</p></div>} breadcrumbs={[{ type: 'link' as const, label: 'Dashboard', href: '/dashboard' }, { type: 'page' as const, label: 'Group blocks' }]}>
    <div className="space-y-5 p-4 md:p-6">
      {!workspace.groupsEnabled && <p className="rounded border border-amber-300 bg-amber-50 p-3 text-amber-950">Group operations are turned off in property settings. Existing reservations remain visible. Enable the property capability after reviewing group contract and billing settings.</p>}
      <details className="rounded border p-4"><summary className="cursor-pointer font-medium">Create a negotiated group block</summary><div className="mt-3 grid gap-3 md:grid-cols-3">
        <Input aria-label="Group name" placeholder="Group / contract name" value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} /><Input aria-label="Group contact name" placeholder="Booker contact name" value={form.contactName} onChange={event => setForm({ ...form, contactName: event.target.value })} /><Input aria-label="Group contact email" type="email" placeholder="Booker email" value={form.contactEmail} onChange={event => setForm({ ...form, contactEmail: event.target.value })} />
        <label>Arrival<Input type="date" value={form.arrivalDate} onChange={event => setForm({ ...form, arrivalDate: event.target.value })} /></label><label>Departure<Input type="date" value={form.departureDate} onChange={event => setForm({ ...form, departureDate: event.target.value })} /></label><label>Pickup cutoff (device timezone)<Input type="datetime-local" value={form.releaseDate} onChange={event => setForm({ ...form, releaseDate: event.target.value })} /></label>
        <select aria-label="Group room type" className="rounded border p-2" value={form.roomTypeId} onChange={event => setForm({ ...form, roomTypeId: event.target.value, ratePlanId: '' })}><option value="">Room type</option>{workspace.roomTypes.map(type => <option key={type.id} value={type.id}>{type.name}</option>)}</select>
        <select aria-label="Contract rate plan" className="rounded border p-2" value={form.ratePlanId} onChange={event => setForm({ ...form, ratePlanId: event.target.value })}><option value="">Contract cancellation / meal terms</option>{roomType?.ratePlans.map(plan => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</select>
        <select aria-label="Group payer routing" className="rounded border p-2" value={form.billingType} onChange={event => setForm({ ...form, billingType: event.target.value })}><option value="guest_pays">Each guest pays their stay</option><option value="master_folio">Whole stays billed to group master folio</option></select>
        <label>Rooms held<Input type="number" min="1" value={form.roomsHeld} onChange={event => setForm({ ...form, roomsHeld: Number(event.target.value) })} /></label><label>Negotiated nightly room rate (USD, before tax/fees)<Input type="number" min="0" step="0.01" value={form.rateDollars} onChange={event => setForm({ ...form, rateDollars: event.target.value })} /></label>
        <Button disabled={busy || !workspace.groupsEnabled || !form.name || !form.roomTypeId || !form.ratePlanId || !form.arrivalDate || !form.departureDate || !form.rateDollars} onClick={create}>Hold group room nights</Button>
      </div><p className="mt-2 text-sm">The negotiated rate, cancellation and meal terms, taxes and fees are frozen when the block is created. Split payer windows are not supported.</p></details>
      <div className="space-y-3">{workspace.groups.map(group => <article key={group.id} className="rounded border p-4"><h2 className="font-medium">{group.name} · {group.blockCode} · {group.status}</h2><p className="text-sm">{group.arrivalDate.slice(0, 10)} – {group.departureDate.slice(0, 10)} · {group.billingType.replaceAll('_', ' ')}{group.releaseDate ? ` · cutoff ${new Date(group.releaseDate).toLocaleString()}` : ''}</p>{group.allocations.map(allocation => <p key={allocation.id} className="text-sm">{allocation.roomType.name}: {allocation.roomsPickedUp} / {allocation.roomsHeld} picked up · {money(allocation.rateMinor)} nightly</p>)}
        <div className="mt-2 flex flex-wrap gap-2">{group.status === 'tentative' && <Button size="sm" disabled={busy || !workspace.groupsEnabled} onClick={() => perform(`definite:${group.id}`, key => updateGroupStatus(group.id, 'definite', key))}>Confirm block</Button>}{['tentative', 'definite'].includes(group.status) && <><Button size="sm" variant="outline" onClick={() => setSelectedGroup(group.id)}>Import rooming list</Button><Button size="sm" variant="outline" disabled={busy} onClick={() => perform(`release:${group.id}`, key => updateGroupStatus(group.id, 'released', key))}>Release unused rooms</Button><Button size="sm" variant="outline" disabled={busy} onClick={() => perform(`cancel:${group.id}`, key => updateGroupStatus(group.id, 'cancelled', key))}>Cancel empty block</Button></>}</div>
        {!!group.bookings.length && <details className="mt-2"><summary>Picked-up reservations</summary>{group.bookings.map(booking => <div key={booking.id} className="text-sm"><Link className="underline" href={`/dashboard/platform/folios?bookingId=${booking.id}`}>{booking.confirmationNumber} · {booking.guestName}</Link> · {booking.status}{group.billingType === 'guest_pays' && ['pending', 'confirmed'].includes(booking.status) && <GroupRecontract bookingId={booking.id} arrival={group.arrivalDate} departure={group.departureDate} roomTypes={workspace.roomTypes} onSaved={refresh} />}</div>)}</details>}
        {group.masterFolio && <div className="mt-2 space-y-2 text-sm"><p>Master folio {group.masterFolio.folioNumber}: {group.masterFolio.status} · posted balance {money(group.masterFolio.entries.reduce((sum, entry) => sum + (entry.direction === 'debit' ? entry.amountMinor : -entry.amountMinor), 0))}</p><p>Postings accumulate as service nights are audited. Use a member&apos;s folio workspace to record group payment, or transfer the master folio to an approved receivable account.</p><Link className="underline" href="/dashboard/platform/receivables">Direct billing and account collection</Link><Button className="ml-3" size="sm" variant="outline" disabled={busy || group.masterFolio.status !== 'open'} onClick={() => perform(`close:${group.id}`, key => closeGroupMasterFolio(group.id, key))}>Close settled master folio</Button></div>}
      </article>)}</div>
      <div className="flex gap-2">{cursor && <Button variant="outline" onClick={() => setCursor(undefined)}>Newest groups</Button>}{workspace.hasMore && <Button variant="outline" onClick={() => setCursor(workspace.nextCursor)}>Older groups</Button>}</div>
      {selected && <section className="rounded border p-4"><h2 className="font-medium">Rooming list: {selected.name}</h2><p className="text-sm">One room per row. Keep each row reference stable. The entire import is accepted together; row errors save no reservations.</p><Input aria-label="Rooming-list CSV file" type="file" accept=".csv,text/csv" onChange={async event => { const file = event.target.files?.[0]; if (file) setCsv(await file.text()); }} /><textarea aria-label="Rooming-list CSV" className="my-2 min-h-40 w-full rounded border p-2 font-mono text-sm" value={csv} onChange={event => setCsv(event.target.value)} /><Button disabled={busy || !workspace.groupsEnabled} onClick={() => { try { const rows = parseRoomingCsv(csv); perform(`rooming:${selected.id}:${csv}`, key => createGroupRoomingList(selected.id, selected.allocations[0].id, rows, key)); } catch (error) { setMessage(error instanceof Error ? error.message : 'Invalid rooming list.'); } }}>Create guest reservations from held rooms</Button></section>}
      {message && <p role="status" className="whitespace-pre-wrap rounded border p-3">{message}</p>}
    </div>
  </PageContainer>;
}
