import { getHotelSettings } from '../lib/hotel-settings';
import { StayLink } from '../components/StayProvider';
import { graphqlQuery } from '@/lib/graphql-client';
import { GET_ROOM_TYPES } from '@/lib/queries';
import { AMENITY_LABELS, primaryRoomImage } from '@/lib/hotel-storefront';
import type { RoomType } from '@/lib/types';
export default async function AmenitiesPage() {
  const identity = await getHotelSettings(); let rooms: RoomType[] = [];
  try { rooms = (await graphqlQuery<{roomTypes:RoomType[]}>(GET_ROOM_TYPES)).roomTypes || []; } catch { /* Scoped catalog fallback below. */ }
  return <main><div className="lodging-container hotel-page-head"><p className="lodging-eyebrow">Around the house</p><h1 className="lodging-display">The details of your stay.</h1><p>Get to know {identity.name}, from the spaces you see to the comforts in your room.</p></div>
    <section className="lodging-container hotel-section hotel-editorial"><img src={identity.media.amenity.imagePath} alt={identity.media.amenity.altText} /><div><p className="lodging-eyebrow">A closer look</p><h2 className="lodging-headline">Make room for your kind of stay.</h2>{identity.media.amenity.caption && <p>{identity.media.amenity.caption}</p>}<p>Room features vary by category. Review the published amenities below, and check your selected rate for any meals included.</p><StayLink href="/gallery" className="lodging-link">Explore the gallery ↗</StayLink></div></section>
    <section className="lodging-container pb-16"><div className="hotel-section-heading"><h2 className="lodging-headline">In your room.</h2><StayLink href="/rooms" className="lodging-link">Compare rooms & rates ↗</StayLink></div><div className="hotel-room-grid">{rooms.map(room=><article key={room.id} className="hotel-room-card"><img src={primaryRoomImage(room)} alt={room.name} loading="lazy" /><h3>{room.name}</h3>{room.amenities?.length ? <ul className="space-y-2 text-sm">{room.amenities.map(item=><li key={item}>{AMENITY_LABELS[item] || item.replaceAll('_',' ')}</li>)}</ul> : <p>Ask the property about the amenities in this room.</p>}<StayLink href={`/rooms/${room.id}`} className="lodging-link mt-4">Room details ↗</StayLink></article>)}</div>{!rooms.length && <p className="hotel-notice">Room amenities are unavailable right now. Contact the property for details.</p>}</section>
    <section className="hotel-band"><div className="lodging-container hotel-section hotel-details-grid"><article><h2>Something specific in mind?</h2><p>Ask about accessibility, dietary needs, parking, or other requirements before reserving. Requests depend on the property’s confirmation.</p><StayLink href="/contact?subject=Stay%20requirements" className="lodging-link">Ask the property ↗</StayLink></article><article><h2>A little planning, a calmer arrival.</h2><p>Find the address and published arrival times, then review the terms attached to your selected rate.</p><StayLink href="/location" className="lodging-link">Arrival details ↗</StayLink><br /><StayLink href="/policies" className="lodging-link">Booking & stay policies ↗</StayLink></article></div></section></main>;
}
