'use client';
import { Suspense,useEffect,useMemo,useRef,useState } from 'react';
import Link from 'next/link';
import { useSearchParams,useRouter } from 'next/navigation';
import { Elements } from '@stripe/react-stripe-js';
import { loadStripe } from '@stripe/stripe-js';
import { graphqlClient } from '@/lib/graphql-client';
import { CREATE_STOREFRONT_BOOKING,GET_BOOKING_PAYMENT_PROVIDERS,GET_ROOM_TYPE,GET_STOREFRONT_QUOTE,GET_GUEST_BOOKING,INITIATE_BOOKING_PAYMENT_SESSION,COMPLETE_BOOKING_PAYMENT } from '@/lib/queries';
import type { Booking,RoomType } from '@/lib/types';
import { selectDisplayedStayPrice, type StayQuote } from '../lib/quote';
import { primaryRoomImage } from '@/lib/hotel-storefront';
import { operationAttempt } from '@/lib/operationAttempt';
import { formatStayDate } from '@/lib/hotelCalendarDate';
import { StripeCheckoutForm } from '@/components/booking/StripeCheckoutForm';
import { useHotelSettings } from '../components/HotelSettingsProvider';
import { StayPrice } from '../components/StayPrice';
import { money,reservationPresentation } from '../lib/stay-context';
import { roomSearchValidationMessage,selectInitialPublicRatePlan,safeQuoteFailureMessage } from '../lib/qa-workflows';
interface Provider{id:string;name:string;code:string;displayName?:string|null;publicClientKey?:string|null}
interface Session{id:string;amount:number;clientSecret?:string|null;approveLink?:string|null}
function BookContent(){
  const params=useSearchParams();const router=useRouter();const identity=useHotelSettings();const originalQuery=params?.toString()||'';
  const [resumeId]=useState(()=>params?.get('bookingId')||'');
  const roomTypeId=params?.get('roomTypeId')||'';const checkIn=params?.get('checkIn')||'';const checkOut=params?.get('checkOut')||'';const adults=params?.get('adults')||'2';const children=params?.get('children')||'0';const requestedRate=params?.get('ratePlanId')||'';const promoCode=params?.get('promoCode')||'';
  const [room,setRoom]=useState<RoomType|null>(null);const [quote,setQuote]=useState<StayQuote|null>(null);const [bookedTerms,setBookedTerms]=useState<Booking['bookedStayTerms']>(null);const [held,setHeld]=useState<Booking|null>(null);const [bookingId,setBookingId]=useState(resumeId);const [reference,setReference]=useState('');const [loading,setLoading]=useState(true);const [loadError,setLoadError]=useState('');const [revision,setRevision]=useState(0);
  const [providers,setProviders]=useState<Provider[]>([]);const [providerCode,setProviderCode]=useState('');const [providerError,setProviderError]=useState('');const [session,setSession]=useState<Session|null>(null);const [paymentError,setPaymentError]=useState('');const [busy,setBusy]=useState(false);const [confirming,setConfirming]=useState(false);const actionLock=useRef(false);const confirmationLock=useRef(false);const [accepted,setAccepted]=useState(false);
  const [form,setForm]=useState({guestName:'',guestEmail:'',guestPhone:'',specialRequests:''});
  const selectedProvider=providers.find(provider=>provider.code===providerCode);const stripe=useMemo(()=>session?.clientSecret&&selectedProvider?.code==='pp_stripe_stripe'&&selectedProvider.publicClientKey?loadStripe(selectedProvider.publicClientKey):null,[session?.clientSecret,selectedProvider]);
  useEffect(()=>{let active=true;setLoading(true);setLoadError('');
    async function load(){try{
      if(resumeId){const data=await graphqlClient.request<{booking:Booking|null}>(GET_GUEST_BOOKING,{bookingId:resumeId});if(!data.booking)throw new Error('access');if(!active)return;setHeld(data.booking);setBookedTerms(data.booking.bookedStayTerms||null);setReference(data.booking.confirmationNumber);setRoom(data.booking.roomAssignments?.[0]?.roomType||null);setForm({guestName:data.booking.guestName,guestEmail:data.booking.guestEmail,guestPhone:data.booking.guestPhone||'',specialRequests:data.booking.specialRequests||''});}
      else {const invalid=roomSearchValidationMessage(checkIn,checkOut,adults,children);if(invalid||!roomTypeId||!checkIn||!checkOut){if(active)setLoadError(invalid||'Choose a room and stay dates before reserving.');return;}
        const data=await graphqlClient.request<{roomType:RoomType}>(GET_ROOM_TYPE,{id:roomTypeId});const plan=selectInitialPublicRatePlan(data.roomType?.ratePlans,requestedRate);if(!plan)throw new Error('rate');const priced=await graphqlClient.request<{storefrontQuote:StayQuote}>(GET_STOREFRONT_QUOTE,{roomTypeId,ratePlanId:plan.id,checkInDate:`${checkIn}T00:00:00Z`,checkOutDate:`${checkOut}T00:00:00Z`,numberOfAdults:Number(adults),numberOfChildren:Number(children),promoCode:promoCode.trim()||null});if(active){setRoom(data.roomType);setQuote(priced.storefrontQuote);}}
      const methods=await graphqlClient.request<{bookingPaymentProviders:Provider[]}>(GET_BOOKING_PAYMENT_PROVIDERS);if(!active)return;const available=(methods.bookingPaymentProviders||[]).filter(provider=>provider.code==='pp_paypal_paypal'||(provider.code==='pp_stripe_stripe'&&provider.publicClientKey));setProviders(available);setProviderCode(current=>available.some(item=>item.code===current)?current:available[0]?.code||'');setProviderError(available.length?'':'Online payment is unavailable. Contact the property before reserving.');
    }catch{if(active)setLoadError(resumeId?'This reservation cannot be opened in this guest session. Use secure lookup to restore access.':safeQuoteFailureMessage());}finally{if(active)setLoading(false);}}
    void load();return()=>{active=false;};
  },[resumeId,roomTypeId,requestedRate,checkIn,checkOut,adults,children,promoCode,revision]);
  const keepReservation=(id:string)=>{setBookingId(id);const next=new URLSearchParams(window.location.search);next.set('bookingId',id);window.history.replaceState(null,'',`/book?${next}`);};
  const startPayment=async(event:React.FormEvent)=>{event.preventDefault();if(actionLock.current||confirmationLock.current)return;if(!providerCode||(!bookingId&&!accepted))return;actionLock.current=true;setBusy(true);setPaymentError('');
    let currentId=bookingId;
    try{
      if(!currentId){if(!quote)throw new Error('quote');
        const bookingData={...form,guestName:form.guestName.trim(),guestEmail:form.guestEmail.trim(),guestPhone:form.guestPhone.trim(),checkInDate:`${checkIn}T00:00:00Z`,checkOutDate:`${checkOut}T00:00:00Z`,numberOfAdults:Number(adults),numberOfChildren:Number(children),roomTypeId,ratePlanId:quote.ratePlanId,quoteToken:quote.quoteToken,promoCode:promoCode.trim()||null};
        const {quoteToken:_signedQuote,...attemptPayload}=bookingData;const attempt=await operationAttempt('guest-booking',attemptPayload);
        const result=await graphqlClient.request<{createStorefrontBooking:Booking}>(CREATE_STOREFRONT_BOOKING,{data:{...bookingData,idempotencyKey:attempt.key}});
        const created=result.createStorefrontBooking;currentId=created.id;keepReservation(currentId);setHeld(created);setBookedTerms(created.bookedStayTerms||null);setRoom(created.roomAssignments?.[0]?.roomType||room);setReference(created.confirmationNumber);
      }
      const origin=window.location.origin;const cancel=new URLSearchParams(window.location.search);cancel.set('bookingId',currentId);
      const result=await graphqlClient.request<{initiateBookingPaymentSession:Session}>(INITIATE_BOOKING_PAYMENT_SESSION,{bookingId:currentId,paymentProviderCode:providerCode,returnUrl:`${origin}/${providerCode==='pp_paypal_paypal'?'paypal':'stripe'}/return?bookingId=${encodeURIComponent(currentId)}`,cancelUrl:`${origin}/book?${cancel}`});
      const next=result.initiateBookingPaymentSession;if(!next?.id||!Number.isInteger(next.amount)||next.amount<0)throw new Error('session');if(providerCode==='pp_paypal_paypal'&&!next.approveLink||providerCode==='pp_stripe_stripe'&&!next.clientSecret)throw new Error('provider');setSession(next);
    }catch{setPaymentError(currentId?'Payment could not be started for this reservation. It may have expired or its balance may have changed. Check reservation status before trying another payment.':'We could not complete this reservation request. Check the current rate and availability, then retry with the same details. If you already received a booking reference, use secure lookup.');}
    finally{actionLock.current=false;setBusy(false);}
  };
  const completePayment=async(providerPaymentId:string)=>{if(confirmationLock.current||!bookingId||!session)return;confirmationLock.current=true;setConfirming(true);setPaymentError('');try{
    await graphqlClient.request(COMPLETE_BOOKING_PAYMENT,{bookingId,paymentSessionId:session.id,providerPaymentId});
    // The destination reads authoritative reservation and financial status, including compensation.
    router.push(`/booking/${encodeURIComponent(bookingId)}`);
  }catch{setPaymentError('We could not verify the final reservation status. Payment may have been received. Open your reservation before attempting another payment.');}finally{confirmationLock.current=false;setConfirming(false);}};
  if(loading)return <main className="lodging-container hotel-section" role="status">Preparing your stay details…</main>;
  if(loadError)return <main className="lodging-container hotel-section"><div className="hotel-notice" role="alert"><p className="lodging-eyebrow">Your reservation</p><h1 className="lodging-title mt-3">Let’s check the details.</h1><p>{loadError}</p><div className="flex flex-wrap gap-5"><button className="lodging-button" onClick={()=>setRevision(value=>value+1)}>Try again</button><Link href={resumeId?'/bookings/lookup':`/rooms?${originalQuery}`} className="lodging-link">{resumeId?'Secure booking lookup':'Review rooms & dates'}</Link></div></div></main>;
  const arrival=held?.checkInDate||checkIn;const departure=held?.checkOutDate||checkOut;const canPay=!held||held.status==='pending'||held.status==='confirmed';const displayedTerms=selectDisplayedStayPrice(bookingId,quote,bookedTerms);const paymentCurrency=displayedTerms?.currencyCode||held?.currencyCode||'USD';
  return <main className="lodging-container pb-16"><nav aria-label="Booking steps" className="hotel-journey"><Link href={`/rooms/${room?.id||roomTypeId}?${originalQuery}`}>01 / Room & rate</Link><span aria-current="step">02 / Guest & payment</span><span>03 / Reservation status</span></nav><header className="hotel-page-head !pt-0"><p className="lodging-eyebrow">{bookingId?'Continue your reservation':'Direct reservations'}</p><h1 className="lodging-display">Your stay starts here.</h1><p>{bookingId?`Reservation ${reference||bookingId}. Review its current status before continuing payment.`:'Review the full stay price and rate terms, then enter the details of the lead guest.'}</p></header>
  <div className="grid gap-10 pt-10 lg:grid-cols-[minmax(0,1.3fr)_minmax(320px,1fr)]"><div className="min-w-0 space-y-8">{held&&<div className="hotel-status"><p className="lodging-eyebrow">{reservationPresentation(held.status).label}</p><p>{reservationPresentation(held.status).copy}</p><Link href={`/booking/${held.id}`} className="lodging-link">Open reservation & statement ↗</Link></div>}
  {canPay&&<><form id="hotel-guest-form" onSubmit={startPayment} className="space-y-7"><fieldset disabled={Boolean(bookingId)||busy} className="space-y-5"><legend className="lodging-title mb-5">Guest details.</legend><div className="grid sm:grid-cols-2 gap-5">{[['guestName','Full name','text','name'],['guestEmail','Email address','email','email'],['guestPhone','Phone number','tel','tel']].map(([name,label,type,autoComplete])=><label key={name} className="hotel-field">{label}<input name={name} type={type} autoComplete={autoComplete} required maxLength={name==='guestName'?120:254} value={form[name as keyof typeof form]} onChange={event=>setForm(previous=>({...previous,[name]:event.target.value}))}/></label>)}</div><label className="hotel-field">Special requests (optional)<textarea className="lodging-textarea" rows={3} maxLength={2000} value={form.specialRequests} onChange={event=>setForm(previous=>({...previous,specialRequests:event.target.value}))}/></label><p className="text-xs">Requests are subject to the property’s confirmation. For requirements essential to your stay, <Link className="underline" href="/contact">contact the property</Link> before reserving.</p></fieldset>
  {!bookingId&&<label className="flex items-start gap-3 text-sm border-y border-[var(--lodging-rule)] py-5"><input type="checkbox" required checked={accepted} onChange={event=>setAccepted(event.target.checked)} className="mt-1"/><span>I have reviewed the full stay price, payment amounts and cancellation terms for the selected rate. <Link href="/policies" target="_blank" className="underline">Booking policies (new tab)</Link></span></label>}
  <fieldset disabled={busy||confirming||Boolean(session)}><legend className="lodging-title mb-5">Payment method.</legend>{providers.map(provider=><label className="flex items-center gap-3 border border-[var(--lodging-rule)] p-4 mb-3 text-sm" key={provider.id}><input type="radio" name="paymentProvider" checked={providerCode===provider.code} onChange={()=>{setProviderCode(provider.code);setPaymentError('');}}/>{provider.displayName||provider.name}</label>)}{providerError&&<div className="hotel-notice" role="alert"><p>{providerError}</p><Link className="lodging-link" href="/contact">Contact the property</Link></div>}</fieldset>
  {!session&&<button className="lodging-button w-full" disabled={busy||!providerCode||(!bookingId&&!accepted)}>{busy?'Preparing secure payment…':bookingId?'Check current amount & continue':'Continue to secure payment →'}</button>}
  </form>
  {bookingId&&<div className="hotel-notice"><p className="text-sm">This reservation is subject to the latest availability and payment checks. A pending booking or an open payment form is not confirmation.</p><Link href={`/booking/${bookingId}`} className="lodging-link">Check reservation status ↗</Link></div>}
  {session&&<section aria-label="Secure payment" className="border border-[var(--lodging-rule)] p-5 space-y-5"><div className="hotel-money-row total"><span>Payment amount</span><strong>{money(session.amount,paymentCurrency)}</strong></div><p className="text-xs">This amount is returned by the current payment session. Final reservation status appears after verification.</p>{session.approveLink?<a className="lodging-button w-full" href={session.approveLink}>Continue to PayPal →</a>:stripe&&session.clientSecret?<Elements stripe={stripe} options={{clientSecret:session.clientSecret}}><StripeCheckoutForm amount={session.amount/100} currencyCode={paymentCurrency} bookingId={bookingId} paymentSessionId={session.id} onSuccess={completePayment} onError={setPaymentError}/></Elements>:<p role="status">Preparing the secure payment form…</p>}{confirming&&<p role="status">Verifying payment and reservation status…</p>}</section>}
  </>}
  {paymentError&&<div role="alert" className="hotel-notice"><p>{paymentError}</p><div className="flex flex-wrap gap-5">{bookingId?<Link className="lodging-button" href={`/booking/${bookingId}`}>Review reservation status</Link>:<button className="lodging-link" onClick={()=>{setAccepted(false);setRevision(value=>value+1);}}>Refresh price & availability</button>}<Link className="lodging-link" href="/bookings/lookup">Find a reservation</Link></div></div>}
  </div><aside className="min-w-0"><div className="border border-[var(--lodging-rule)] p-6 space-y-6">{room&&<><img src={primaryRoomImage(room)} alt={room.name} className="w-full aspect-[1.5] object-cover"/><h2 className="lodging-title">{room.name}</h2></>}<dl className="space-y-3 text-sm"><div className="flex justify-between gap-6"><dt>Arrival</dt><dd>{formatStayDate(arrival,{month:'short',day:'numeric',year:'numeric'})}</dd></div><div className="flex justify-between gap-6"><dt>Departure</dt><dd>{formatStayDate(departure,{month:'short',day:'numeric',year:'numeric'})}</dd></div><div className="flex justify-between gap-6"><dt>Guests in one room</dt><dd>{held?.numberOfGuests||Number(adults)+Number(children)}</dd></div></dl>{displayedTerms?<StayPrice quote={displayedTerms} paymentAmountMinor={session?.amount}/>:held&&<section aria-label="Recorded booking total"><div className="hotel-money-row"><span>Taxes included</span><span>{money(held.taxAmountMinor??Math.round((held.taxAmount||0)*100),paymentCurrency)}</span></div><div className="hotel-money-row"><span>Fees included</span><span>{money(held.feesAmountMinor??Math.round((held.feesAmount||0)*100),paymentCurrency)}</span></div><div className="hotel-money-row total"><span>Recorded stay total</span><span>{money(held.totalAmountMinor??Math.round((held.totalAmount||0)*100),paymentCurrency)}</span></div><p className="text-xs mt-4">The original rate breakdown is unavailable. These are persisted booking amounts, not a current quote. The current collectible amount is checked before payment; review your reservation for recorded rate terms and statement.</p></section>}<p className="text-xs border-t border-[var(--lodging-rule)] pt-5">Check-in from {identity.checkIn}; check-out by {identity.checkOut}, local property time.</p><Link href={`/rooms/${room?.id||roomTypeId}?${originalQuery}`} className="lodging-link">Review room details</Link></div></aside></div></main>;
}
export default function BookPage(){return <Suspense fallback={<main className="lodging-container hotel-section" role="status">Preparing your booking…</main>}><BookContent/></Suspense>}
