'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { useParams,useSearchParams,useRouter } from 'next/navigation';
import { graphqlClient } from '@/lib/graphql-client';
import { GET_ROOM_TYPE,GET_STOREFRONT_QUOTE } from '@/lib/queries';
import type { RoomType } from '@/lib/types';
import type { StayQuote } from '../lib/quote';
import { AMENITY_LABELS,BED_CONFIG_LABELS,roomCopy,roomImages } from '@/lib/hotel-storefront';
import { RoomImageGallery } from '@/components/booking/RoomImageGallery';
import { StayPrice } from '../components/StayPrice';
import { roomSearchValidationMessage,selectInitialPublicRatePlan,safeQuoteFailureMessage } from '../lib/qa-workflows';
import { cancellationTerms,stayNights } from '../lib/stay-context';
import { useStay } from '../components/StayProvider';
export default function RoomDetailPage(){
 const route=useParams<{slug:string}>();const search=useSearchParams();const [revision,setRevision]=useState(0);
 const slug=route?.slug||'';const query=search?.toString()||'';
 return <RoomDetailContent key={`${slug}:${query}:${revision}`} slug={slug} query={query} onRetry={()=>setRevision(value=>value+1)}/>;
}
function RoomDetailContent({slug,query,onRetry}:{slug:string;query:string;onRetry:()=>void}){
  const router=useRouter();const {setStay}=useStay();const source=new URLSearchParams(query);
  const initial={checkIn:source.get('checkIn')||'',checkOut:source.get('checkOut')||'',adults:source.get('adults')||'2',children:source.get('children')||'0',ratePlanId:source.get('ratePlanId')||'',promoCode:source.get('promoCode')||''};
  const [room,setRoom]=useState<RoomType|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  const [form,setForm]=useState(initial);const [quote,setQuote]=useState<StayQuote|null>(null);const [quotedKey,setQuotedKey]=useState('');const [pricing,setPricing]=useState(true);const [quoteError,setQuoteError]=useState('');
  useEffect(()=>{let active=true;graphqlClient.request<{roomType:RoomType|null}>(GET_ROOM_TYPE,{id:slug}).then(data=>{if(active){setRoom(data.roomType);if(!data.roomType)setError('This room is not available in the collection.');else{const plan=selectInitialPublicRatePlan(data.roomType.ratePlans,new URLSearchParams(query).get('ratePlanId'));setForm(previous=>({...previous,ratePlanId:plan?.id||''}));}}}).catch(()=>{if(active)setError('We could not load this room. Please try again.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[slug,query]);
  const initialPlan=selectInitialPublicRatePlan(room?.ratePlans,initial.ratePlanId);const quoteForm={...initial,ratePlanId:initialPlan?.id||''};
  const validation=roomSearchValidationMessage(initial.checkIn,initial.checkOut,initial.adults,initial.children);
  const preflight=validation||(!initial.checkIn||!initial.checkOut?'Choose arrival and departure dates for a full stay price.':!initialPlan?'No published rate is available. Contact the property for help reserving this room.':stayNights(initial.checkIn,initial.checkOut)<initialPlan.minimumStay?`This rate requires at least ${initialPlan.minimumStay} nights. Choose another rate or extend your stay.`:room&&Number(initial.adults)+Number(initial.children)>room.maxOccupancy?`This room accommodates up to ${room.maxOccupancy} guests. Adjust your party or compare other rooms.`:initialPlan.isPromotional&&!initial.promoCode.trim()?'Enter the promotion code for this rate.':'');
  const requestKey=JSON.stringify(quoteForm);const planId=initialPlan?.id;
  useEffect(()=>{if(!room||preflight||!planId)return;let active=true;const next=JSON.parse(requestKey);
    graphqlClient.request<{storefrontQuote:StayQuote}>(GET_STOREFRONT_QUOTE,{roomTypeId:room.id,ratePlanId:planId,checkInDate:`${next.checkIn}T00:00:00Z`,checkOutDate:`${next.checkOut}T00:00:00Z`,numberOfAdults:Number(next.adults),numberOfChildren:Number(next.children),promoCode:next.promoCode.trim()||null}).then(data=>{if(active){setQuote(data.storefrontQuote);setQuotedKey(requestKey);}}).catch(()=>{if(active)setQuoteError(safeQuoteFailureMessage());}).finally(()=>{if(active)setPricing(false);});return()=>{active=false;};
  },[room,preflight,planId,requestKey]);
  const current=Boolean(quote&&quotedKey===JSON.stringify(form));const plan=room?.ratePlans?.find(item=>item.id===form.ratePlanId);const update=(key:keyof typeof form,value:string)=>setForm(previous=>({...previous,[key]:value}));const notice=quoteError||preflight;
  const refresh=(event:React.FormEvent)=>{event.preventDefault();const invalid=roomSearchValidationMessage(form.checkIn,form.checkOut,form.adults,form.children);if(invalid){setQuoteError(invalid);return;}const params=new URLSearchParams(query);Object.entries(form).forEach(([key,value])=>value?params.set(key,value):params.delete(key));setStay(params.toString());if(params.toString()===query)onRetry();else router.push(`/rooms/${slug}?${params}#rates`,{scroll:false});};
  const bookingParams=new URLSearchParams(query);Object.entries(form).forEach(([key,value])=>value?bookingParams.set(key,value):bookingParams.delete(key));bookingParams.set('roomTypeId',slug);
  if(loading)return <main className="lodging-container hotel-section" role="status"><p>Opening the room…</p></main>;
  if(error||!room)return <main className="lodging-container hotel-section"><div className="hotel-notice" role="alert"><h1 className="lodging-title">The room could not be opened.</h1><p>{error}</p><button className="lodging-button mr-5" onClick={onRetry}>Try again</button><Link href={`/rooms?${query}`} className="lodging-link">Return to rooms</Link></div></main>;
  return <main className="lodging-container"><div className="hotel-page-head"><Link href={`/rooms?${query}`} className="lodging-link">← Back to results</Link><p className="lodging-eyebrow mt-5">{room.eyebrow||'Your room at the house'}</p><h1 className="lodging-display">{room.name}</h1><p>{roomCopy(room)}</p><div className="hotel-room-facts">{room.bedConfiguration&&<span>{BED_CONFIG_LABELS[room.bedConfiguration]||room.bedConfiguration}</span>}<span>Up to {room.maxOccupancy} guests</span>{room.squareFeet&&<span>{room.squareFeet} sq ft</span>}</div></div><nav className="hotel-subnav" aria-label="Room sections"><a href="#photos">Photographs</a><a href="#details">Room details</a><a href="#rates">Dates & rates</a></nav>
  <div className="grid gap-10 py-10 lg:grid-cols-[minmax(0,1.45fr)_minmax(340px,1fr)]"><div className="space-y-10"><section id="photos"><h2 className="sr-only">Room photographs</h2><RoomImageGallery images={roomImages(room)} roomName={room.name}/></section><a href="#rates" className="lodging-button w-full lg:hidden">Choose dates & review rates ↓</a><section id="details"><p className="lodging-eyebrow">A space of your own</p><h2 className="lodging-headline mt-3 mb-6">The room, in detail.</h2>{room.viewDescription&&<p className="mb-6">{room.viewDescription}</p>}{room.amenities?.length?<ul className="grid grid-cols-2 gap-3 border-y border-[var(--lodging-rule)] py-6 text-sm">{room.amenities.map(item=><li key={item}>{AMENITY_LABELS[item]||item.replaceAll('_',' ')}</li>)}</ul>:<p>Contact the property for a full list of room amenities.</p>}<div className="hotel-notice"><h3 className="lodging-title">A particular requirement?</h3><p>Confirm accessibility, bedding requests, and any arrangements essential to your stay before booking.</p><Link className="lodging-link" href="/contact?subject=Room%20requirements">Ask the property ↗</Link></div></section></div>
  <aside id="rates" className="min-w-0"><div className="hotel-notice !mt-0 !p-6"><p className="lodging-eyebrow">01 / Choose your stay</p><h2 className="lodging-title mt-3 mb-6">Dates & rates.</h2><form onSubmit={refresh} className="space-y-5"><fieldset className="grid grid-cols-2 gap-3"><legend className="sr-only">Stay dates</legend><label className="hotel-field">Arrival<input type="date" required value={form.checkIn} onChange={event=>update('checkIn',event.target.value)}/></label><label className="hotel-field">Departure<input type="date" required value={form.checkOut} min={form.checkIn||undefined} onChange={event=>update('checkOut',event.target.value)}/></label></fieldset><fieldset className="grid grid-cols-2 gap-3"><legend className="sr-only">Guests in one room</legend><label className="hotel-field">Adults<input type="number" min="1" max={room.maxOccupancy} required value={form.adults} onChange={event=>update('adults',event.target.value)}/></label><label className="hotel-field">Children<input type="number" min="0" max={room.maxOccupancy} required value={form.children} onChange={event=>update('children',event.target.value)}/></label></fieldset><fieldset><legend className="lodging-eyebrow mb-3">Choose a rate</legend><div className="space-y-3">{room.ratePlans?.map(rate=><label key={rate.id} className="flex gap-3 border border-[var(--lodging-rule-strong)] p-4 cursor-pointer"><input className="mt-1" type="radio" name="ratePlan" value={rate.id} checked={form.ratePlanId===rate.id} onChange={()=>update('ratePlanId',rate.id)}/><span><strong className="text-sm font-medium">{rate.name}</strong>{rate.description&&<span className="block mt-1 text-xs">{rate.description}</span>}<span className="block mt-2 text-xs">{cancellationTerms(rate.cancellationPolicy)}</span><span className="block mt-2 text-xs">{rate.minimumStay>1?`${rate.minimumStay}-night minimum · `:''}{rate.mealPlan?.replaceAll('_',' ')}{rate.isPromotional?' · Promotion code required':''}</span></span></label>)}</div></fieldset><label className="hotel-field">Promotion code {plan?.isPromotional?'(required)':'(optional)'}<input autoComplete="off" value={form.promoCode} maxLength={100} onChange={event=>update('promoCode',event.target.value)} /></label><button className="lodging-button-ghost w-full" disabled={pricing&&!preflight}>{pricing&&!preflight?'Checking this stay…':'Update stay & rates'}</button></form>
  <div className="mt-6" aria-live="polite">{current&&quote?<><StayPrice quote={quote}/><Link href={`/book?${bookingParams}`} className="lodging-button w-full mt-6">Continue with this stay →</Link><p className="text-xs mt-3">Availability and price are checked again when you reserve. No payment is taken on this page.</p></>:<p className="text-sm" role={notice?'status':undefined}>{pricing&&!preflight?'Checking availability and the full stay price…':quotedKey?'Your choices changed. Update the stay to review a fresh price.':notice||'Update your stay to review the full price.'}</p>}</div><Link href="/policies" className="lodging-link mt-4">Booking & stay policies</Link></div></aside></div></main>;
}
