'use client';
import { Suspense, useEffect, useMemo, useState } from 'react';
import { useSearchParams,useRouter } from 'next/navigation';
import Link from 'next/link';
import { graphqlClient } from '@/lib/graphql-client';
import { GET_ROOM_TYPES,GET_AVAILABLE_ROOMS,GET_STOREFRONT_QUOTE } from '@/lib/queries';
import type { RoomType } from '@/lib/types';
import type { StayQuote } from '../lib/quote';
import { AMENITY_LABELS,BED_CONFIG_LABELS } from '@/lib/hotel-storefront';
import { RoomCard } from '@/components/booking/RoomCard';
import { SearchWidget } from '@/components/booking/SearchWidget';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { roomSearchValidationMessage,selectInitialPublicRatePlan } from '../lib/qa-workflows';
import { stayNights,money,cancellationTerms } from '../lib/stay-context';
type AvailableRoom=RoomType&{availableCount?:number};
function RoomsContent(){
  const params=useSearchParams();const router=useRouter();const query=params?.toString()||'';
  const from=params?.get('checkIn')||'';const to=params?.get('checkOut')||'';const adults=params?.get('adults')||'2';const children=params?.get('children')||'0';
  const queryError=roomSearchValidationMessage(from,to,adults,children);const dated=Boolean(from&&to&&!queryError);const nights=stayNights(from,to);
  const [rooms,setRooms]=useState<AvailableRoom[]>([]);const [quotes,setQuotes]=useState<Record<string,StayQuote>>({});const [loading,setLoading]=useState(true);const [pricing,setPricing]=useState(false);const [error,setError]=useState('');const [retry,setRetry]=useState(0);
  const amenityQuery=params?.get('amenities')||'';const amenities=useMemo(()=>amenityQuery.split(',').filter(Boolean),[amenityQuery]);const sort=params?.get('sortBy')||'price_asc';const price=params?.get('priceRange')||'';const comparison=(params?.get('compare')||'').split(',').filter(Boolean).slice(0,3);
  const update=(values:Record<string,string|null>)=>{const next=new URLSearchParams(query);Object.entries(values).forEach(([key,value])=>value?next.set(key,value):next.delete(key));router.push(`/rooms?${next}#results`,{scroll:false});};
  useEffect(()=>{let active=true;setLoading(true);setError('');setQuotes({});setPricing(false);setRooms([]);
    async function fetchRooms(){if(queryError){setLoading(false);return;}try{
      const catalog=(await graphqlClient.request<{roomTypes:RoomType[]}>(GET_ROOM_TYPES)).roomTypes||[];
      let rows:AvailableRoom[]=catalog;
      if(dated){const data=await graphqlClient.request<{roomTypes:AvailableRoom[]}>(GET_AVAILABLE_ROOMS,{checkInDate:`${from}T00:00:00Z`,checkOutDate:`${to}T00:00:00Z`});rows=(data.roomTypes||[]).map(room=>({...room,ratePlans:catalog.find(item=>item.id===room.id)?.ratePlans}));}
      if(!active)return;setRooms(rows);setLoading(false);
      if(dated){setPricing(true);const queue=rows.filter(room=>(room.availableCount||0)>0&&room.maxOccupancy>=Number(adults)+Number(children));let cursor=0;
        await Promise.all(Array.from({length:Math.min(3,queue.length)},async()=>{while(active&&cursor<queue.length){const room=queue[cursor++];const plan=selectInitialPublicRatePlan(room.ratePlans?.filter(plan=>!plan.isPromotional&&plan.minimumStay<=nights), null);if(!plan||plan.minimumStay>nights)continue;try{const data=await graphqlClient.request<{storefrontQuote:StayQuote}>(GET_STOREFRONT_QUOTE,{roomTypeId:room.id,ratePlanId:plan.id,checkInDate:`${from}T00:00:00Z`,checkOutDate:`${to}T00:00:00Z`,numberOfAdults:Number(adults),numberOfChildren:Number(children)});if(active)setQuotes(previous=>({...previous,[room.id]:data.storefrontQuote}));}catch{/* A missing quote is not a zero price or proof of sold-out inventory. */}}}));
        if(active)setPricing(false);
      }
    }catch{if(active){setError('We could not load the room collection. Your search choices are still here.');setLoading(false);setPricing(false);}}}
    void fetchRooms();return()=>{active=false;};
  },[from,to,adults,children,queryError,dated,nights,retry]);
  const shown=useMemo(()=>{let rows=rooms.filter(room=>room.maxOccupancy>=Number(adults)+Number(children)&&(!dated||(room.availableCount||0)>0)&&amenities.every(item=>room.amenities?.includes(item)));
    if(price){const [min,max]=price.split('-').map(Number);if(Number.isFinite(min)&&Number.isFinite(max))rows=rows.filter(room=>room.baseRate>=min&&room.baseRate<=max);}
    const direction=sort.endsWith('desc')?-1:1;return rows.sort((a,b)=>{if(sort.startsWith('occupancy'))return direction*(a.maxOccupancy-b.maxOccupancy);if(sort.startsWith('size'))return direction*((a.squareFeet||0)-(b.squareFeet||0));if(dated){const aq=quotes[a.id],bq=quotes[b.id];if(!aq||!bq)return aq?-1:bq?1:0;if(aq.currencyCode!==bq.currencyCode)return aq.currencyCode.localeCompare(bq.currencyCode);return direction*(aq.totalAmountMinor-bq.totalAmountMinor);}return direction*(a.baseRate-b.baseRate);});
  },[rooms,adults,children,dated,amenities,price,sort,quotes]);
  const selected=rooms.filter(room=>comparison.includes(room.id));const options=[...new Set(rooms.flatMap(room=>room.amenities||[]))].sort();
  return <main><header className="lodging-container hotel-page-head"><p className="lodging-eyebrow">Rooms & suites</p><h1 className="lodging-display">Find your place in the house.</h1><p>Compare the details that matter. Choose dates to see availability and a full stay price, including taxes and fees.</p></header><div className="lodging-container pt-8" id="choose-dates"><SearchWidget query={query} /></div><section className="lodging-container hotel-section" id="results">
    <div data-qa-layout="room-results-grid" className="grid min-w-0 gap-8 lg:grid-cols-[210px_minmax(0,1fr)]"><aside><details open className="border-y border-[var(--lodging-rule)] py-4"><summary className="cursor-pointer min-h-11 font-medium">Refine your stay</summary><fieldset className="mt-5"><legend className="lodging-eyebrow mb-4">Room comforts</legend>{options.map(item=><label key={item} className="flex gap-3 items-center min-h-11 text-sm"><input type="checkbox" checked={amenities.includes(item)} onChange={()=>update({amenities:(amenities.includes(item)?amenities.filter(a=>a!==item):[...amenities,item]).join(',')})}/>{AMENITY_LABELS[item]||item.replaceAll('_',' ')}</label>)}</fieldset><form className="mt-6 space-y-3" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);update({priceRange:`${data.get('min')||0}-${data.get('max')||100000}`});}}><p className="text-sm">Base nightly rate filter</p><p className="text-xs text-[var(--lodging-ink-muted)]">Reference rate only; the dated total may differ.</p><div className="grid grid-cols-2 gap-2" key={price}><label className="hotel-field">Minimum<input name="min" type="number" min="0" defaultValue={price.split('-')[0]||''}/></label><label className="hotel-field">Maximum<input name="max" type="number" min="0" defaultValue={price.split('-')[1]||''}/></label></div><button className="lodging-button-ghost w-full">Apply budget</button></form></details></aside>
    <div data-qa-layout="room-results-content" className="min-w-0"><div data-qa-layout="room-results-toolbar" className="flex flex-wrap items-center justify-between gap-4 mb-6"><p role="status" className="text-sm">{loading?'Checking rooms…':`${shown.length} room ${shown.length===1?'type':'types'}${dated?` · ${nights} nights`:''}`}</p><Select value={sort} onValueChange={value=>update({sortBy:value})}><SelectTrigger aria-label="Sort available rooms" data-qa-layout="room-results-sort" className="w-full sm:w-60 rounded-none"><SelectValue /></SelectTrigger><SelectContent>{[['price_asc',dated?'Stay total: low to high':'Base rate: low to high'],['price_desc',dated?'Stay total: high to low':'Base rate: high to low'],['occupancy_asc','Guests: fewer to more'],['occupancy_desc','Guests: more to fewer'],['size_asc','Size: smaller first'],['size_desc','Size: larger first']].map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div>
    {(amenities.length>0||price)&&<div className="flex flex-wrap gap-4 text-sm mb-6">{amenities.map(item=><button key={item} className="min-h-11 underline" onClick={()=>update({amenities:amenities.filter(a=>a!==item).join(',')})}>Remove {AMENITY_LABELS[item]||item}</button>)}<button className="lodging-link" onClick={()=>update({amenities:null,priceRange:null})}>Clear filters</button></div>}
    {comparison.length>0&&<div className="hotel-notice"><a href="#compare" className="lodging-link">Compare {selected.length} selected room{selected.length===1?'':'s'} ↓</a><button className="lodging-link ml-5" onClick={()=>update({compare:null})}>Clear comparison</button></div>}
    {queryError?<div role="alert" className="hotel-notice"><p>{queryError}</p><a href="#choose-dates" className="lodging-link">Edit your search above</a></div>:error?<div role="alert" className="hotel-notice"><p>{error}</p><button className="lodging-button" onClick={()=>setRetry(value=>value+1)}>Try again</button></div>:loading?<div role="status" className="hotel-notice">Loading room details…</div>:!shown.length?<div className="hotel-notice"><h2 className="lodging-title">No rooms match this stay.</h2><p>Try other dates, fewer guests in one room, or clear your filters. For multiple rooms, contact the property.</p><button className="lodging-link mr-6" onClick={()=>update({amenities:null,priceRange:null})}>Clear filters</button><Link className="lodging-link" href="/contact">Ask the property ↗</Link></div>:shown.map(room=><div key={room.id}><RoomCard roomType={room} availableCount={dated?room.availableCount:undefined} searchParams={query} layout="list" quote={quotes[room.id]?{...quotes[room.id],numberOfNights:quotes[room.id].nights}:undefined} pricing={dated&&pricing&&!quotes[room.id]}/><label className="flex items-center gap-3 min-h-12 text-sm"><input type="checkbox" checked={comparison.includes(room.id)} disabled={!comparison.includes(room.id)&&comparison.length>=3} onChange={()=>update({compare:(comparison.includes(room.id)?comparison.filter(id=>id!==room.id):[...comparison,room.id]).join(',')})}/>Compare {room.name}</label></div>)}
    {selected.length>0&&<section id="compare" className="mt-12"><h2 className="lodging-title">A closer comparison.</h2><p className="text-sm mt-3">Select up to three rooms. Quotes below apply to the named rate; review other plans on the room page.</p><div className="hotel-compare" tabIndex={0} role="region" aria-label="Room comparison, scroll horizontally on small screens"><table><thead><tr><th scope="col">Your stay</th>{selected.map(room=><th scope="col" key={room.id}>{room.name}</th>)}</tr></thead><tbody>{['Full stay total','Bed','Guests','Size','Amenities','Cancellation','Explore'].map(label=><tr key={label}><th scope="row">{label}</th>{selected.map(room=><td key={room.id}>{label==='Full stay total'?quotes[room.id]?<>{money(quotes[room.id].totalAmountMinor,quotes[room.id].currencyCode)}<br />{quotes[room.id].ratePlanName}<br />Taxes & fees included</>:dated?'Review rates for a current total':'Choose dates':label==='Bed'?BED_CONFIG_LABELS[room.bedConfiguration||'']||room.bedConfiguration||'Ask the property':label==='Guests'?`Up to ${room.maxOccupancy}`:label==='Size'?room.squareFeet?`${room.squareFeet} sq ft`:'Not published':label==='Amenities'?(room.amenities||[]).map(a=>AMENITY_LABELS[a]||a).join(', ')||'Not published':label==='Cancellation'?cancellationTerms(quotes[room.id]?.cancellationPolicy):<Link className="lodging-link" href={`/rooms/${room.id}?${query}`}>View {room.name} ↗</Link>}</td>)}</tr>)}</tbody></table></div></section>}
    </div></div></section></main>;
}
export default function RoomsPage(){return <Suspense fallback={<p className="lodging-container hotel-section" role="status">Loading room search…</p>}><RoomsContent /></Suspense>}
