'use client';
import Link from 'next/link';
import type { RoomType } from '@/lib/types';
import { BED_CONFIG_LABELS, primaryRoomImage, roomCopy } from '@/lib/hotel-storefront';
import { useStay } from '@/features/storefront/components/StayProvider';
import { stayHref, money } from '@/features/storefront/lib/stay-context';
export interface RoomPrice { totalAmountMinor:number; currencyCode:string; numberOfNights:number; ratePlanName:string; cancellationPolicy?:string; ratePlanId?:string; }
interface Props {roomType:RoomType; availableCount?:number; nights?:number; totalPrice?:number; searchParams?:string; layout?:'card'|'list'; quote?:RoomPrice; pricing?:boolean;}
export function RoomCard({roomType:room,availableCount,searchParams,layout='card',quote,pricing}:Props){const {stay}=useStay();const resultQuery=new URLSearchParams(searchParams||'');if(quote) resultQuery.set('ratePlanId',(quote as RoomPrice & {ratePlanId?:string}).ratePlanId || room.ratePlans?.find(plan=>plan.name===quote.ratePlanName)?.id || '');const href=searchParams!==undefined?`/rooms/${room.id}${resultQuery.size?`?${resultQuery}`:''}`:stayHref(`/rooms/${room.id}`,stay);return <article className={`hotel-room-card ${layout==='list'?'hotel-list-room':''}`}><Link href={href} aria-label={`Explore ${room.name}`}><img src={primaryRoomImage(room)} alt={room.roomImages?.[0]?.altText || room.name} loading="lazy" /></Link><div>{room.eyebrow&&<p className="lodging-eyebrow mt-4">{room.eyebrow}</p>}<h3><Link href={href}>{room.name}</Link></h3><p>{roomCopy(room)}</p><div className="hotel-room-facts">{room.bedConfiguration&&<span>{BED_CONFIG_LABELS[room.bedConfiguration]||room.bedConfiguration}</span>}<span>Up to {room.maxOccupancy} guests</span>{room.squareFeet ? <span>{room.squareFeet} sq ft</span>:null}</div>{availableCount===0&&<p>Unavailable for these dates</p>}<div className="hotel-room-actions"><div>{quote?<><strong>{money(quote.totalAmountMinor,quote.currencyCode)}</strong><small>{quote.numberOfNights} nights · taxes & fees included<br />{quote.ratePlanName}</small></>:<small>{pricing?'Checking full stay price…':searchParams?.includes('checkIn')?'Review available rates for a full stay total.':'Choose dates to see a full stay price.'}</small>}</div><Link href={href} className="lodging-link">{quote?'Choose this room':'Explore room'} ↗</Link></div></div></article>}
