'use client';
import * as React from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { loadMaintenanceCommercial, saveMaintenanceCommercial } from './commercialActions';

const fields: Record<string, Array<[string, string]>> = { plan: [['vendorName', 'Vendor or internal team'], ['vendorReference', 'Work-order or vendor reference'], ['dueAt', 'Repair deadline with time zone (2026-09-10T15:00:00-04:00)']], acknowledge: [], order_part: [['partId', 'Unique part line reference'], ['description', 'Part description'], ['quantity', 'Whole quantity'], ['unitCostMinor', 'Unit cost in minor units']], part_status: [['partId', 'Part line reference'], ['status', 'received, used, cancelled or returned']], labor: [['laborCostMinor', 'Total labor cost in minor units']] };
export default function MaintenanceCommercialPanel({ requestId }: { requestId: string }) {
  const [record, setRecord] = React.useState<any>(null); const [command, setCommand] = React.useState('plan'); const [values, setValues] = React.useState<Record<string, string>>({}); const [reason, setReason] = React.useState('');
  const [busy, setBusy] = React.useState(false); const [message, setMessage] = React.useState(''); const attempt = React.useRef({ signature: '', key: '' });
  async function run(fn: () => Promise<void>) { setBusy(true); setMessage(''); try { await fn(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Work-order details failed.'); } finally { setBusy(false); } }
  async function save() { const payload: any = { ...values, reason, expectedRevision: record.commercial.revision }; for (const field of ['quantity', 'unitCostMinor', 'laborCostMinor']) if (field in payload) payload[field] = Number(payload[field]); const signature = JSON.stringify({ requestId, command, payload }); if (attempt.current.signature !== signature) attempt.current = { signature, key: crypto.randomUUID() }; setRecord(await saveMaintenanceCommercial(requestId, command, payload, attempt.current.key)); attempt.current = { signature: '', key: '' }; setValues({}); setReason(''); }
  return <details className="w-full rounded-md border p-3"><summary className="cursor-pointer text-sm font-medium">Vendor, repair deadline and parts</summary><div className="mt-3 space-y-3"><Button size="sm" variant="outline" disabled={busy} onClick={() => void run(async () => setRecord(await loadMaintenanceCommercial(requestId)))}>Load work-order details</Button><p role="status" className="text-sm">{message}</p>{record && <><p className="text-sm">{record.commercial.vendorName || 'No vendor assigned'} · {record.commercial.vendorReference || 'No work-order reference'} · Due {record.commercial.dueAt || 'not set'} {record.overdue ? '— OVERDUE' : ''}</p><p className="text-sm">Acknowledged {record.commercial.acknowledgedAt || 'not yet'} · Actual recorded labor and used parts: {record.actualCostMinor} minor units</p><p className="text-xs text-muted-foreground">These are staff-recorded work-order facts. This does not send an order, pay a vendor, or release a room; the inspection workflow still controls room availability.</p>{record.commercial.parts.map((part: any) => <p key={part.id} className="text-sm">{part.id}: {part.description} · {part.quantity} × {part.unitCostMinor} minor units · {part.status}</p>)}<form className="max-w-xl space-y-2" onSubmit={event => { event.preventDefault(); void run(save); }}><Label htmlFor={`commercial-command-${requestId}`}>Action</Label><select id={`commercial-command-${requestId}`} className="block w-full rounded-md border bg-background p-2" value={command} onChange={event => { setCommand(event.target.value); setValues({}); }}>{Object.keys(fields).map(value => <option value={value} key={value}>{value.replaceAll('_', ' ')}</option>)}</select>{fields[command].map(([key, label]) => <div key={key}><Label htmlFor={`${requestId}-${key}`}>{label}</Label><Input id={`${requestId}-${key}`} value={values[key] || ''} onChange={event => setValues(current => ({ ...current, [key]: event.target.value }))} required /></div>)}<Label htmlFor={`${requestId}-evidence`}>Evidence reference or change reason</Label><Input id={`${requestId}-evidence`} value={reason} onChange={event => setReason(event.target.value)} required /><Button size="sm" disabled={busy}>Record work-order change</Button></form><details><summary className="cursor-pointer text-sm">Commercial change history</summary>{record.history.map((row: any, index: number) => <p className="text-sm" key={index}>{row.occurredAt}: {row.action} · {row.reason}</p>)}</details></>}</div></details>;
}
