'use client';
import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { operationAttempt } from '@/lib/operationAttempt';
import { getRelocation, updateRelocation } from '../actions';
const empty = { propertyName: '', contact: '', confirmation: '', costDollars: '', guestAgreement: '', followUp: '', costEvidence: '' };
export default function RelocationPanel({ bookingId }: { bookingId: string }) {
  const [form, setForm] = useState(empty), [state, setState] = useState<{ revision: number; status: string } | null>(null), [message, setMessage] = useState(''), [busy, setBusy] = useState(false);
  useEffect(() => { getRelocation(bookingId).then(value => { if (value) { setState(value); setForm({ ...value, costDollars: (value.costMinor / 100).toFixed(2) }); } }).catch(error => setMessage(error.message)); }, [bookingId]);
  async function save(status: string) { setBusy(true); try { const input = { ...form, bookingId, status, expectedRevision: state?.revision || 0, costMinor: Math.round(Number(form.costDollars || 0) * 100) }, attempt = await operationAttempt('relocation', input); const result = await updateRelocation({ ...input, idempotencyKey: attempt.key }); attempt.complete(); setState(result); setMessage('Relocation evidence saved.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Relocation evidence could not be saved.'); } finally { setBusy(false); } }
  const next = !state ? 'requested' : state.status === 'requested' ? 'arranged' : state.status === 'arranged' ? 'transferred' : state.status === 'transferred' ? 'completed' : null;
  return <details className="rounded border p-3 text-sm"><summary className="cursor-pointer font-medium">Guest relocation / walk {state ? `· ${state.status}` : ''}</summary><p className="my-2">Record a manually arranged receiving property and guest agreement. The local reservation keeps its room nights until normal cancellation or departure completes. External accommodation cost is recorded as staff evidence; settle it through the property&apos;s expense process.</p><div className="grid gap-2 md:grid-cols-2">{([['propertyName', 'Receiving property and address'], ['contact', 'Receiving property contact'], ['confirmation', 'Receiving reservation confirmation'], ['guestAgreement', 'Guest agreement and transportation plan'], ['followUp', 'Guest arrival and follow-up evidence'], ['costEvidence', 'Cost settlement reference or no-cost explanation']] as const).map(([key, label]) => <Input key={key} aria-label={label} placeholder={label} value={form[key]} disabled={state?.status === 'completed'} onChange={event => setForm({ ...form, [key]: event.target.value })} />)}<Input aria-label="Relocation cost USD" type="number" min="0" step="0.01" placeholder="Relocation cost USD" value={form.costDollars} disabled={state?.status === 'completed'} onChange={event => setForm({ ...form, costDollars: event.target.value })} /></div>{next && <Button className="mt-2" disabled={busy} onClick={() => save(next)}>Record {next}</Button>}{message && <p role="status" className="mt-2">{message}</p>}</details>;
}
