'use client';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { operationAttempt } from '@/lib/operationAttempt';
import { detachGroupBooking } from '../actions';
export default function GroupRecontract({ bookingId, arrival, departure, roomTypes, onSaved }: { bookingId: string; arrival: string; departure: string; roomTypes: Array<{ id: string; name: string; ratePlans: Array<{ id: string; name: string }> }>; onSaved: () => void }) {
  const [start, setStart] = useState(arrival.slice(0, 10)), [end, setEnd] = useState(departure.slice(0, 10)), [type, setType] = useState(''), [rate, setRate] = useState(''), [reason, setReason] = useState(''), [busy, setBusy] = useState(false), [message, setMessage] = useState('');
  async function save() { setBusy(true); try { const input = { bookingId, checkInDate: `${start}T00:00:00.000Z`, checkOutDate: `${end}T00:00:00.000Z`, roomTypeId: type, ratePlanId: rate, reason }, attempt = await operationAttempt('group-recontract', input); const result = await detachGroupBooking({ ...input, idempotencyKey: attempt.key }); attempt.complete(); setMessage(`Independent reservation saved at USD ${(result.totalAmountMinor / 100).toFixed(2)}.`); onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Recontract failed; the original group commitment remains.'); } finally { setBusy(false); } }
  return <details className="my-2 rounded border p-2"><summary>Leave group and reprice independently</summary><p className="text-sm">This guest-paid reservation will leave its negotiated group contract. Its original allotment returns to the group; the new stay must fit remaining public inventory. Current standard rate, deposit and security-deposit terms apply. Refund any amount exceeding the new total first.</p><div className="my-2 flex flex-wrap gap-2"><Input aria-label="Independent arrival" type="date" value={start} onChange={event => setStart(event.target.value)} /><Input aria-label="Independent departure" type="date" value={end} onChange={event => setEnd(event.target.value)} /><select aria-label="Independent room type" value={type} onChange={event => { setType(event.target.value); setRate(''); }}><option value="">Room type</option>{roomTypes.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="Independent rate plan" value={rate} onChange={event => setRate(event.target.value)}><option value="">Rate plan</option>{roomTypes.find(item => item.id === type)?.ratePlans.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><Input aria-label="Guest agreement and recontract reason" placeholder="Guest agreement and reason" value={reason} onChange={event => setReason(event.target.value)} /><Button disabled={busy || !start || !end || !type || !rate || !reason.trim()} onClick={save}>Return allotment and reprice guest stay</Button></div>{message && <p role="status">{message}</p>}</details>;
}
