'use client';
import { useState } from 'react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { operationAttempt } from '@/lib/operationAttempt';
import { getHousekeepingStaffCapabilities, updateHousekeepingStaffCapability } from '../actions';
export default function StaffCapabilityEditor() {
  const [workspace, setWorkspace] = useState<any>(null), [staffId, setStaffId] = useState(''), [configured, setConfigured] = useState(true), [floors, setFloors] = useState('*'), [allRooms, setAllRooms] = useState(true), [roomIds, setRoomIds] = useState<string[]>([]), [tasks, setTasks] = useState<string[]>([]), [section, setSection] = useState(''), [message, setMessage] = useState(''), [busy, setBusy] = useState(false);
  async function refresh() { try { setWorkspace(await getHousekeepingStaffCapabilities()); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load staff capabilities.'); } }
  function select(id: string) { setStaffId(id); const value = workspace.staff.find((person: any) => person.id === id)?.capability; setConfigured(value?.configured ?? true); setFloors(value?.allowedFloors === null || !value ? '*' : value.allowedFloors.join(',')); setAllRooms(value?.allowedRoomIds === null || !value); setRoomIds(value?.allowedRoomIds || []); setTasks(value?.taskTypes || workspace.taskTypes); setSection(value?.sectionName || ''); }
  async function save() { setBusy(true); try { const configuration = { configured, allowedFloors: floors.trim() === '*' ? null : floors.trim() ? floors.split(',').map(value => Number(value.trim())) : [], allowedRoomIds: allRooms ? null : roomIds, taskTypes: tasks, sectionName: allRooms ? '' : section }, expectedRevision = workspace.staff.find((person: any) => person.id === staffId)?.capability?.revision || 0, attempt = await operationAttempt('housekeeping-capability', { staffId, configuration, expectedRevision }); await updateHousekeepingStaffCapability(staffId, configuration, expectedRevision, attempt.key); attempt.complete(); await refresh(); setMessage('Staff skills and section restrictions saved.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Staff capability could not be saved.'); } finally { setBusy(false); } }
  return <details className="mt-3 rounded border p-3" onToggle={event => { if (event.currentTarget.open && !workspace) refresh(); }}><summary>Staff skills and assigned sections</summary>{workspace?.canConfigure ? <div className="mt-3 space-y-2"><p className="text-sm">People or role managers can restrict dispatch. Without custom rules, the active housekeeping or maintenance role determines eligibility. * means every floor; an empty list permits none. Floor and room-section restrictions both apply.</p><select aria-label="Staff capability profile" value={staffId} onChange={event => select(event.target.value)}><option value="">Select staff member</option>{workspace.staff.map((person: any) => <option key={person.id} value={person.id}>{person.name}</option>)}</select>{staffId && <><label className="block"><input type="checkbox" checked={configured} onChange={event => setConfigured(event.target.checked)} /> Apply custom dispatch restrictions</label><Input aria-label="Allowed floors" placeholder="Allowed floors: *, 1,2,3, or empty for none" value={floors} onChange={event => setFloors(event.target.value)} /><fieldset><legend className="text-sm">Qualified task types</legend>{workspace.taskTypes.map((type: string) => <label key={type} className="mr-3 inline-block text-sm"><input type="checkbox" checked={tasks.includes(type)} onChange={event => setTasks(event.target.checked ? [...tasks, type] : tasks.filter(item => item !== type))} /> {type.replaceAll('_', ' ')}</label>)}</fieldset><label className="block"><input type="checkbox" checked={allRooms} onChange={event => setAllRooms(event.target.checked)} /> All physical rooms</label>{!allRooms && <><Input aria-label="Section name" placeholder="Section name (for example east wing)" value={section} onChange={event => setSection(event.target.value)} /><select aria-label="Rooms in assigned section" multiple className="min-h-32 w-full rounded border" value={roomIds} onChange={event => setRoomIds(Array.from(event.target.selectedOptions, option => option.value))}>{workspace.rooms.map((room: any) => <option key={room.id} value={room.id}>Room {room.roomNumber} · floor {room.floor}</option>)}</select></>}<Button disabled={busy} onClick={save}>Save staff dispatch policy</Button></>}</div> : workspace && <p className="mt-2 text-sm">Staff skill and section changes require people or role management permission. Dispatch rechecks these restrictions when commands sync.</p>}{message && <p role="status" className="mt-2 text-sm">{message}</p>}</details>;
}
