'use client';

import * as React from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { applyHotelApproval, loadHotelApprovals } from './actions';

export default function HotelApprovalsPage() {
  const [rows, setRows] = React.useState<any[]>([]); const [action, setAction] = React.useState('refund'); const [target, setTarget] = React.useState('');
  const [amount, setAmount] = React.useState('0'); const [reason, setReason] = React.useState(''); const [status, setStatus] = React.useState('active'); const [isPublic, setIsPublic] = React.useState(true);
  const [message, setMessage] = React.useState(''); const [busy, setBusy] = React.useState(false); const attempts = React.useRef(new Map<string, string>());
  const [offset, setOffset] = React.useState(0); const [nextOffset, setNextOffset] = React.useState<number | null>(null);
  async function run(operation: () => Promise<void>, pageOffset = offset) { setBusy(true); setMessage(''); try { await operation(); const page = await loadHotelApprovals(pageOffset); setRows(page.rows); setOffset(pageOffset); setNextOffset(page.nextOffset); } catch (error) { setMessage(error instanceof Error ? error.message : 'Approval operation failed.'); } finally { setBusy(false); } }
  async function apply(payload: Record<string, unknown>) { const signature = JSON.stringify(payload); const key = attempts.current.get(signature) || crypto.randomUUID(); attempts.current.set(signature, key); const result = await applyHotelApproval(payload, key); attempts.current.delete(signature); setMessage(`Approval reference ${result.approvalId}`); }
  return <main className="space-y-6 p-6"><h1 className="text-2xl font-semibold">Independent hotel approvals</h1><p className="text-muted-foreground">Request approval for an exact target and amount. A different staff member with approval authority decides; the operating action consumes the approval once.</p>
    <div className="flex gap-2"><Button disabled={busy} variant="outline" onClick={() => void run(async () => {}, 0)}>Newest approval requests</Button>{offset > 0 && <Button disabled={busy} variant="outline" onClick={() => void run(async () => {}, Math.max(0, offset - 100))}>Newer page</Button>}{nextOffset !== null && <Button disabled={busy} variant="outline" onClick={() => void run(async () => {}, nextOffset)}>Older page</Button>}</div><p role="status">{message}</p>
    <form className="max-w-xl space-y-3 rounded-md border p-4" onSubmit={event => { event.preventDefault(); void run(() => apply({ action, aggregateId: target, amountMinor: action === 'rate_publish' ? 0 : Number(amount), reason, ...(action === 'rate_publish' ? { parameters: { status, isPublic } } : {}) })); }}>
      <Label htmlFor="approval-action">Action</Label><select id="approval-action" className="block w-full rounded-md border bg-background p-2" value={action} onChange={event => setAction(event.target.value)}>{['refund', 'write_off', 'rate_publish', 'cash_variance', 'security_capture', 'payout_reconcile'].map(value => <option key={value} value={value}>{value.replaceAll('_', ' ')}</option>)}</select>
      <Label htmlFor="approval-target">Payment, booking, folio, rate plan, cashier session or security authorization ID</Label><Input id="approval-target" value={target} onChange={event => setTarget(event.target.value)} required />
      {action === 'rate_publish' ? <><Label htmlFor="approval-rate-status">Rate status</Label><select id="approval-rate-status" className="block w-full rounded-md border bg-background p-2" value={status} onChange={event => setStatus(event.target.value)}>{['active', 'inactive', 'draft'].map(value => <option key={value}>{value}</option>)}</select><Label className="flex gap-2"><input type="checkbox" checked={isPublic} onChange={event => setIsPublic(event.target.checked)} />Publicly bookable</Label></> : <><Label htmlFor="approval-amount">Amount in minor units (100 = USD 1)</Label><Input id="approval-amount" type="number" min={0} step={1} value={amount} onChange={event => setAmount(event.target.value)} required /></>}
      <Label htmlFor="approval-reason">Request or decision reason</Label><Input id="approval-reason" value={reason} onChange={event => setReason(event.target.value)} required />{action === 'payout_reconcile' ? <p className="text-sm">Create this exact statement request from the payout reconciliation workspace, then review it below.</p> : <Button disabled={busy}>Request approval</Button>}
    </form>
    <div className="space-y-3">{rows.filter(row => row.action === 'request').map(row => { const decision = rows.find(item => item.approvalId === row.approvalId && item.action === 'decision'); const used = rows.some(item => item.approvalId === row.approvalId && item.action === 'used'); return <div key={row.approvalId} className="rounded-md border p-4"><p className="font-medium">{row.evidence.action.replaceAll('_', ' ')} · {row.evidence.amountMinor} minor units</p><p className="break-all text-sm">Target {row.evidence.aggregateId} · Approval {row.approvalId}</p><p>{row.evidence.reason}</p>{row.evidence.action === 'payout_reconcile' && <p className="break-all text-sm">Statement hash {row.evidence.parameters?.sourceHash} · Bank reference {row.evidence.parameters?.bankReference} · Bank amount {row.evidence.parameters?.bankAmountMinor} minor units</p>}{row.evidence.action === 'rate_publish' && row.evidence.parameters && <p>Status {row.evidence.parameters.status} · Public {String(row.evidence.parameters.isPublic)}</p>}{row.evidence.parameters?.derivedRate && <p>Derived parent {row.evidence.parameters.derivedRate.sourcePlanId || 'none'} · multiplier {row.evidence.parameters.derivedRate.multiplierBasisPoints} basis points · adjustment {row.evidence.parameters.derivedRate.adjustmentMinor} minor units · enabled {String(row.evidence.parameters.derivedRate.enabled)}</p>}{row.evidence.economicReview && <details><summary className="cursor-pointer text-sm">Rate economics included in this approval</summary>{Object.entries(row.evidence.economicReview).map(([side, terms]: any) => <dl className="my-2 rounded-md border p-2 text-sm" key={side}><dt className="font-medium">{side}</dt>{Object.entries(terms).map(([name, value]) => <div key={name}><dt className="inline">{name}: </dt><dd className="inline break-all">{typeof value === 'object' ? JSON.stringify(value) : String(value ?? 'unset')}</dd></div>)}</dl>)}</details>}<p>{used ? 'Used' : decision?.evidence.status || 'Pending independent decision'}</p>{!decision && <div className="mt-2 flex gap-2"><Button disabled={busy || !reason} onClick={() => void run(() => apply({ approvalId: row.approvalId, status: 'approved', reason }))}>Approve</Button><Button variant="outline" disabled={busy || !reason} onClick={() => void run(() => apply({ approvalId: row.approvalId, status: 'declined', reason }))}>Decline</Button></div>}</div>; })}</div>
  </main>;
}
